# Generated by Django 4.0.6 on 2022-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tracker', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(to='product_tracker.product'),
        ),
    ]
