# Generated by Django 4.0.6 on 2022-07-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_alert_frequency',
            field=models.CharField(choices=[('d', 'daily'), ('w', 'weekly')], default='d', max_length=1),
        ),
    ]
