# Generated by Django 4.0.6 on 2022-08-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_email_alert_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_product_sale_summary_email',
            field=models.BooleanField(default=True, verbose_name='Receive weekly product sale summary email'),
        ),
    ]
