# Generated by Django 4.0.6 on 2022-07-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tracker', '0003_alter_product_url'),
        ('users', '0003_alter_user_email_alert_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product_tracker.product'),
        ),
    ]
