# Generated by Django 4.0.6 on 2022-08-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_receive_product_sale_summary_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product_sale_summary_email_day_of_week',
        ),
        migrations.AddField(
            model_name='user',
            name='summary_email_day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0, verbose_name='Day of week to receive product sale summary email'),
        ),
    ]
