# Generated by Django 4.0.6 on 2022-08-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_product_sale_summary_email_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary_email_day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, verbose_name='Day of week to receive product sale summary email'),
        ),
    ]
