# Generated by Django 4.0.6 on 2022-07-18 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(max_length=2000, null=True)),
                ('name', models.CharField(max_length=200)),
                ('last_price_check', models.DateTimeField(null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('was_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WoolworthsProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product_tracker.product',),
        ),
    ]
