# Generated by Django 4.0.6 on 2022-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('last_price_check', models.DateTimeField(null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('was_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WoolworthsProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product_tracker.product',),
        ),
    ]
