# Generated by Django 4.0.6 on 2022-07-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tracker', '0003_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='savings_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='savings_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
