# Generated by Django 4.0.6 on 2022-07-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tracker', '0004_alter_product_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
