# Generated by Django 4.0.6 on 2022-07-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tracker', '0004_product_savings_dollars_product_savings_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(choices=[('woolworths', 'Woolworths')], max_length=200),
        ),
    ]
