# Generated by Django 4.0.6 on 2022-08-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tracker', '0005_alter_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_notified_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(choices=[('Woolworths', 'Woolworths')], max_length=200),
        ),
    ]
