# Generated by Django 4.0.6 on 2022-08-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tracker', '0007_alter_product_product_type_by_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dummy_field',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
