# Generated by Django 4.0.6 on 2022-08-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tracker', '0008_product_dummy_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dummy_field_two',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
